---
- hosts: galaxyservers
  vars_files:
    - vars.yml
  become: true
  become_user: root
  become_method: sudo
  vars:
   ansible_become_pass: "{{ your_password }}"
  pre_tasks:
    - name: Install Dependencies
      become: true
      become_user: root
      vars:
        ansible_become_pass: "{{ your_password }}"
      package:
        name: ['git', 'make', 'python3-psycopg2', 'python3-virtualenv', 'tar', 'bzip2', 'python3-venv']

  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  roles:
    - { role: galaxyproject.postgresql, become: yes, become_user: root,        ansible_become_pass: "{{ your_password }}" }
    - { role: natefoo.postgresql_objects, become: true, become_user: postgres, ansible_become_pass: "{{ your_password }}"  }
    - { role: geerlingguy.pip,            become: yes, become_user: root,      ansible_become_pass: "{{ your_password }}" }
    - { role: galaxyproject.galaxy,       become: yes, become_user: root,     ansible_become_pass: "{{ your_password }}" }
    - { role: uchida.miniconda,           become: yes, become_user: galaxy,      ansible_become_pass: "{{ your_password }}" }
    - { role: usegalaxy_eu.galaxy_systemd,    become: yes, become_user: root,      ansible_become_pass: "{{ your_password }}" }
    - { role: galaxyproject.cvmfs, become: yes } 

