---
- hosts: galaxyservers
  become: true
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python3-psycopg2', 'tar', 'virtualenv']
    - git:
        repo: 'https://github.com/usegalaxy-eu/libraries-training-repo'
        dest: /libraries/
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - usegalaxy_eu.galaxy_systemd
    - usegalaxy_eu.rabbitmq
    - galaxyproject.nginx 
    - galaxyproject.cvmfs
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
    - name: Copy tool config file for galaxy
      copy:
        src: templates/galaxy/config/local_tool_conf.xml.j2 
        #dest: /mnt/mountpoint/srv/galaxy/server/config/tool_conf.xml
        dest: "{{ galaxy_root }}/config/local_tool_conf.xml" 
    - name: Copy static html file
      copy:
              #src: /home/ubuntu/220221_ansible_text_v2/Galaxy_Install_Ansible/files/galaxy/config/welcome.html 
        src: files/galaxy/config/welcome.html 
        #dest: /mnt/mountpoint/srv/galaxy/server/config/welcome.html
        dest: "{{ galaxy_root }}/server/static/welcome.html" 
    - name: Copy egc logo for welcome.html file
      copy:
        src: files/galaxy/config/logo.png
        dest: "{{ galaxy_root }}/server/static/logo.png" 
